name: CI for Multi-Ruby Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
        - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t ruby-multi-version .
